#define AVX    1
#define AVX_FLAG    1
#define TDD 1
#define _FAPI_PRINT_ 1
#define _TASK_TIMING 1
#define L2_INTEGRATION 1
#define L1_L2_DECOUPLE 1
#define FB_API 1
#define BBU_POOL_SUPPORT 1
#define PUCCH_PHY_INTEGRATION 1
#define PRACH_PHY_INTEGRATION 1
#define ASTRI_PHY 1
#define PUSCH_SYMB_SCALE 1
#define PRACH_DUMP 1
#define ASTRI_TIME_EST 1
#define DUMP_DATA_LV    3
#define FAPI_PHYMACINTF 1
#define ASTRI_TDD_MODE 1
#define ASTRI_DWPTS 1
#define ASTRI_UPPTS 1
#define PUCCH_WAY 1
#define PROFILE_LV 3
#define PROFILE_RT 1
#define ASTRI_RANGE_CHECK_LV 3
#define ASTRI_INTF 1
#define TIME_OUT_CHECK_MODE    2
#define _FAPI_PRINT_ 1
#define FAPI_RNG_CHECK    1
#define FAPI_ERR_CHECK 1
#define ASTRI_RRU    1
#define TIME_PROFILE_MODE 1
#define IPC_SEMAPHORE 1
#define ASTRI_GNB_PHY 0
